const USER_ROLE = {
  ADMIN: "ADMIN",
  OFFICE_ORDER: "OFFICE_ORDER",
  ADMINISTRATIVE_DEPARTMENT: "ADMINISTRATIVE_DEPARTMENT",
  FINANCIAL_DIRECTION: "FINANCIAL_DIRECTION",
  ACCOUNTING_DEPARTMENT: "ACCOUNTING_DEPARTMENT",
  TAX_DEPARTMENT: "TAX_DEPARTMENT",
  SCHEDILING_SERVICE: "SCHEDILING_SERVICE",
  FINANCIAL_SERVICE: "FINANCIAL_SERVICE",
  EXECUTIVE_MANAGMENT: "EXECUTIVE_MANAGMENT",
};
const FACTURE_STATUS = {
  PENDING: "PENDING",
  APPROVED_ADMINISTRATIF: "APPROVED_ADMINISTRATIF",
  REFUSED: "REFUSED",
  IN_INSTANCE: "IN_INSTANCE",
  APPROVED_DAF: "APPROVED_DAF",
  IN_INSTANCE_DAF: "IN_INSTANCE_DAF",
  COMPTABILISED: "COMPTABILISED",
  APPROVED_FISCAL: "APPROVED_FISCAL",
  APPROVED_PAYMENT: "APPROVED_PAYMENT",
  APPROVED_SERVICE_FINANCIAL: "APPROVED_SERVICE_FINANCIAL",
};
module.exports = {
  USER_ROLE,
  FACTURE_STATUS,
};
